### ISSUE TITLE
Need @RemoteMethod example

### ISSUE THREAD

**Issue by drmikecrowe** [NextFaze/loopback-decorators#8]
Can you please provide a RemoteMethod example?

**Comment by zbarbuto** [comment]
Hi there,

Check out the README:

https://github.com/NextFaze/loopback-decorators#example-remote-method

**Comment by drmikecrowe** [comment]
I tried that and used that extensively. Couldn't get it to work

**Comment by zbarbuto** [comment]
Hi Mike,

Can you provide an example repo of where you tried to get this working? Did you attach the method to a model decorated with `@RemoteMethodModule`? The flow should be:

my-remote.ts
```typescript
@RemoteMethod({
  selector: 'myCustomRemote',
  meta: {/* loopback remote options */}
})
export class MyRemote { async onRemote() { /* Remote Logic */ } }
```

my-model.ts
```typescript
@RemoteMethodModule({
  remotes: [ MyRemote ]
})
export class ModelAPI {
  constructor(public Model: any) { }
}

export = function(Model: any) {
  return new ModelAPI(Model);
};
```

**Comment by drmikecrowe** [comment]
Thanks, zarbuto, that helps.
